insert into public.companies (name, country, industry, website, visibility, priority, status)
values
  ('Panasonic', 'Japan', 'Manufacturing', 'https://holdings.panasonic/global/', 'Shared', null, 'Not Reviewed'),
  ('Shimano', 'Japan', 'Manufacturing', 'https://www.shimano.com', 'Shared', null, 'Not Reviewed'),
  ('Infineon', 'Germany', 'Manufacturing', 'https://www.infineon.com', 'Shared', null, 'Not Reviewed'),
  ('Casco', 'Germany', 'Manufacturing', 'https://www.cascoauto.com', 'Shared', null, 'Not Reviewed'),
  ('Yokogawa', 'Japan', 'Manufacturing', 'https://www.yokogawa.com', 'Shared', null, 'Not Reviewed'),
  ('KEMET', 'United States', 'Manufacturing', 'https://www.kemet.com', 'Shared', null, 'Not Reviewed'),
  ('TDK', 'Japan', 'Manufacturing', 'https://www.tdk.com', 'Shared', null, 'Not Reviewed'),
  ('Valeo', 'France', 'Manufacturing', 'https://www.valeo.com', 'Shared', null, 'Not Reviewed'),
  ('Flex', 'Singapore', 'Manufacturing', 'https://flex.com', 'Shared', null, 'Not Reviewed'),
  ('GE Oil & Gas', 'United States', 'Extractive industries', 'https://www.bakerhughes.com', 'Shared', null, 'Not Reviewed'),
  ('CSL', 'Australia', 'Manufacturing', 'https://www.csl.com', 'Shared', 'Priority 1', 'Not Reviewed'),
  ('Ansell', 'Australia', 'Manufacturing', 'https://www.ansell.com', 'Shared', 'Priority 2', 'Not Reviewed'),
  ('Cochlear', 'Australia', 'Manufacturing', 'https://www.cochlear.com', 'Shared', 'Priority 3', 'Not Reviewed'),
  ('Breville Group', 'Australia', 'Manufacturing', 'https://www.brevillegroup.com', 'Shared', 'Priority 4', 'Not Reviewed'),
  ('Austal', 'Australia', 'Manufacturing', 'https://www.austal.com', 'Shared', 'Priority 5', 'Not Reviewed'),
  ('BlueScope', 'Australia', 'Manufacturing', 'https://www.bluescope.com', 'Shared', 'Priority 6', 'Not Reviewed'),
  ('Orica', 'Australia', 'Extractive industries', 'https://www.orica.com', 'Shared', 'Priority 7', 'Not Reviewed'),
  ('Nufarm', 'Australia', 'Manufacturing', 'https://www.nufarm.com', 'Shared', 'Priority 8', 'Not Reviewed'),
  ('Codan', 'Australia', 'Manufacturing', 'https://www.codan.com.au', 'Shared', 'Priority 9', 'Not Reviewed'),
  ('GPC Electronics', 'Australia', 'Manufacturing', 'https://www.gpcelectronics.com.au', 'Shared', 'Priority 10', 'Not Reviewed'),
  ('REDARC Electronics', 'Australia', 'Manufacturing', 'https://www.redarcelectronics.com', 'Shared', 'Priority 11', 'Not Reviewed');

insert into public.target_accounts (name, country, industry, website, notes, priority)
values
  ('Panasonic', 'Japan', 'Manufacturing', 'https://holdings.panasonic/global/', 'Global HQ: Kadoma, Osaka, Japan. Panasonic Holdings Corporation global HQ.', 'Monitor'),
  ('Shimano', 'Japan', 'Manufacturing', 'https://www.shimano.com', 'Global HQ: Sakai, Osaka, Japan. Shimano Inc. HQ.', 'Monitor'),
  ('Infineon', 'Germany', 'Manufacturing', 'https://www.infineon.com', 'Global HQ: Neubiberg, Germany. Infineon Technologies AG HQ.', 'Monitor'),
  ('Casco', 'Germany', 'Manufacturing', 'https://www.cascoauto.com', 'Global HQ: Frankfurt, Germany. Casco Products HQ; parent Amphenol is HQ in Wallingford, Connecticut, USA.', 'Monitor'),
  ('Yokogawa', 'Japan', 'Manufacturing', 'https://www.yokogawa.com', 'Global HQ: Musashino, Tokyo, Japan. Yokogawa Electric Corporation HQ.', 'Monitor'),
  ('KEMET', 'United States', 'Manufacturing', 'https://www.kemet.com', 'Global HQ: Fort Lauderdale, Florida, USA. KEMET HQ; parent YAGEO Group is HQ in New Taipei City, Taiwan.', 'Monitor'),
  ('TDK', 'Japan', 'Manufacturing', 'https://www.tdk.com', 'Global HQ: Chuo-ku, Tokyo, Japan. TDK Corporation HQ.', 'Monitor'),
  ('Valeo', 'France', 'Manufacturing', 'https://www.valeo.com', 'Global HQ: Paris, France. Valeo SE HQ.', 'Monitor'),
  ('Flex', 'Singapore', 'Manufacturing', 'https://flex.com', 'Global HQ: Singapore / Austin, Texas, USA. Legal domicile and Singapore HQ; principal executive offices in Austin.', 'Monitor'),
  ('GE Oil & Gas', 'United States', 'Extractive industries', 'https://www.bakerhughes.com', 'Global HQ: Houston, Texas, USA. Now largely under Baker Hughes.', 'Monitor'),
  ('CSL', 'Australia', 'Manufacturing', 'https://www.csl.com', 'Priority 1. Global biopharma manufacturing and planning complexity.', 'Priority 1'),
  ('Ansell', 'Australia', 'Manufacturing', 'https://www.ansell.com', 'Priority 2. Offshore-heavy manufacturing footprint and supply-chain planning complexity.', 'Priority 2'),
  ('Cochlear', 'Australia', 'Manufacturing', 'https://www.cochlear.com', 'Priority 3. Advanced medical device manufacturing with global operations.', 'Priority 3'),
  ('Breville Group', 'Australia', 'Manufacturing', 'https://www.brevillegroup.com', 'Priority 4. Appliance supply-chain diversification into Mexico and Southeast Asia.', 'Priority 4'),
  ('Austal', 'Australia', 'Manufacturing', 'https://www.austal.com', 'Priority 5. Complex project manufacturing and shipyards in Australia, USA, Philippines and Vietnam.', 'Priority 5'),
  ('BlueScope', 'Australia', 'Manufacturing', 'https://www.bluescope.com', 'Priority 6. Steel and building-products manufacturing across multiple regions.', 'Priority 6'),
  ('Orica', 'Australia', 'Extractive industries', 'https://www.orica.com', 'Priority 7. Global explosives, specialty chemicals, mining, inventory and logistics complexity.', 'Priority 7'),
  ('Nufarm', 'Australia', 'Manufacturing', 'https://www.nufarm.com', 'Priority 8. Crop protection manufacturing and regional performance management.', 'Priority 8'),
  ('Codan', 'Australia', 'Manufacturing', 'https://www.codan.com.au', 'Priority 9. Advanced electronics and communications manufacturing.', 'Priority 9'),
  ('GPC Electronics', 'Australia', 'Manufacturing', 'https://www.gpcelectronics.com.au', 'Priority 10. Contract electronics manufacturing in Australia, New Zealand and China.', 'Priority 10'),
  ('REDARC Electronics', 'Australia', 'Manufacturing', 'https://www.redarcelectronics.com', 'Priority 11. Advanced electronics across defence, automotive, power electronics and space.', 'Priority 11');
